# Generated by Django 5.1.1 on 2025-10-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(help_text='e.g., lb, gal, oz', max_length=24)),
                ('category', models.CharField(max_length=64)),
                ('unit_size_std', models.FloatField(help_text='standard size in base unit specified')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('series_id', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['series_id', 'date'], name='core_index_series__7cdb44_idx')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('basket_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('mom', models.FloatField(blank=True, null=True)),
                ('yoy', models.FloatField(blank=True, null=True)),
                ('nowcast', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'date'], name='core_metric_region_cfc11b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=64)),
                ('zip', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_size_observed', models.FloatField()),
                ('url', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(default='ok', max_length=24)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'date'], name='core_price_item_id_15e9f0_idx'), models.Index(fields=['zip', 'date'], name='core_price_zip_4016e0_idx')],
            },
        ),
    ]
