# Generated by Django 5.1.1 on 2025-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='item',
            name='store_item_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
